channels:
- conda-forge
dependencies:
- python=3.13.0
- pip<=24.2
- pip:
  - mlflow==2.19.0
  - cloudpickle==3.1.2
  - numpy==2.1.2
  - pandas==2.2.3
  - pyarrow==18.1.0
  - scikit-learn==1.7.1
  - scipy==1.14.1
name: mlflow-env
